### ISSUE TITLE
What exactly does this change from normal sm64ex?

### ISSUE THREAD

**Issue by Cuteistfox** [Render96/Render96ex#115]
Just wondering how this is diffrent. Also this should be in the wiki

**Comment by Project516** [comment]
umm render96? @Velocifyer  it adds hd textures and stuff

**Comment by Cuteistfox** [comment]
i mean render96ex, what does it change from vannilla sm64ex (render96 models and texture are in a seprate repo)

**Comment by Project516** [comment]
it adds more options like cheats and chaos mode

**Comment by Cuteistfox** [comment]
oh
