### ISSUE TITLE
JP build is broken

### ISSUE THREAD

**Issue by Craftyawesome** [Render96/Render96ex#25]
First build has this:
tools/aiff_extract_codebook sound/samples/course_start/00_la.aiff >build/jp_pc/sound/samples/course_start/00_la.table
tools/aiff_extract_codebook sound/samples/instruments/00.aiff >build/jp_pc/sound/samples/instruments/00.table
Traceback (most recent call last):
  File "/home/Aaron Luke/Render96ex/tools/demo_data_converter.py", line 78, in <module>
    main()
  File "/home/Aaron Luke/Render96ex/tools/demo_data_converter.py", line 60, in main
    with open("assets/demos/" + item["name"] + ".bin", "rb") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'assets/demos/bitdw.bin'
make: *** [Makefile:750: build/jp_pc/assets/demo_data.c] Error 1
make: *** Deleting file 'build/jp_pc/assets/demo_data.c'

Running US build first will give you:

python3 tools/assemble_sound.py --sequences build/jp_pc/sound/sequences.bin build/jp_pc/sound/bank_sets sound/sound_banks/ sound/sequences.json sound/sequences/jp/01_cutscene_collect_star.m64 sound/sequences/jp/02_menu_title_screen.m64 sound/sequences/jp/03_level_grass.m64 sound/sequences/jp/04_level_inside_castle.m64 sound/sequences/jp/05_level_water.m64 sound/sequences/jp/06_level_hot.m64 sound/sequences/jp/07_level_boss_koopa.m64 sound/sequences/jp/08_level_snow.m64 sound/sequences/jp/09_level_slide.m64 sound/sequences/jp/0A_level_spooky.m64 sound/sequences/jp/0B_event_piranha_plant.m64 sound/sequences/jp/0C_level_underground.m64 sound/sequences/jp/0D_menu_star_select.m64 sound/sequences/jp/0E_event_powerup.m64 sound/sequences/jp/0F_event_metal_cap.m64 sound/sequences/jp/10_event_koopa_message.m64 sound/sequences/jp/11_level_koopa_road.m64 sound/sequences/jp/12_event_high_score.m64 sound/sequences/jp/13_event_merry_go_round.m64 sound/sequences/jp/14_event_race.m64 sound/sequences/jp/15_cutscene_star_spawn.m64 sound/sequences/jp/16_event_boss.m64 sound/sequences/jp/17_cutscene_collect_key.m64 sound/sequences/jp/18_event_endless_stairs.m64 sound/sequences/jp/19_level_boss_koopa_final.m64 sound/sequences/jp/1A_cutscene_credits.m64 sound/sequences/jp/1B_event_solve_puzzle.m64 sound/sequences/jp/1C_event_toad_message.m64 sound/sequences/jp/1D_event_peach_message.m64 sound/sequences/jp/1E_cutscene_intro.m64 sound/sequences/jp/1F_cutscene_victory.m64 sound/sequences/jp/20_cutscene_ending.m64 sound/sequences/jp/21_menu_file_select.m64   build/jp_pc/sound/sequences/00_sound_player.m64 -DVERSION_US -D_LANGUAGE_C -DGIT_HASH="\"f5735aa8\"" -DNON_MATCHING -DAVOID_UB $(cat build/jp_pc/endian-and-bitwidth)
sequences.json assigns sound banks to 22_cutscene_lakitu, but there is no such sequence file. Either remove the entry (or set it to null), or create sound/sequences/22_cutscene_lakitu.m64.
make: *** [Makefile:711: build/jp_pc/sound/sequences.bin] Error 1

**Comment by KiritoDv** [comment]
There is no JP build support on r96ex, you need to use a us rom
