### ISSUE TITLE
3D Trees Face the Camera

### ISSUE THREAD

**Issue by rileyman6** [Render96/Render96ex#26]
**Describe the bug**
With Render96 v2.2 models enabled or VaniLla96 1.0.1 MP enabled the trees will always rotate to face the camera as though they are 2D despite a 3D model being enabled.

**Expected behavior**
Trees do not rotate to face the camera when Render96 v2.2 or VaniLla96 1.0.1 are enabled.

**Details:**
 - Windows 10
 - Render96ex v2.2 alpha build
 - Odyssey Moveset v5.1.2

**Additional context**
It is worth noting in older builds of Render96 before DynOs was implemented fully that 3D trees did not face the camera yet they do in the current versions. It is also worth noting that other 3D assets rotate as well, e.g. the 1-Up mushroom, though it doesn't really matter if those rotate or not since they aren't as intrusive as the trees.

**Comment by KiritoDv** [comment]
This is not a bug, you need to disable the billboards on the settings.

**Comment by rileyman6** [comment]
Thank you for clearing up my issue.

**Comment by Gagert** [comment]
How do I disable billboards on the settings to fix this issue? I didn't find any settings in either the in-game options menu in sm64ex or the DynOs menu entry. I have searched a bit online now regarding fixing this issue by disabling the billboards on sm64ex. Do I have to edit something while building sm64ex in the command line?
