### ISSUE TITLE
make RENDER_API=RT64 -j4 not working

### ISSUE THREAD

**Issue by XxIvan2398Xx** [Render96/Render96ex#29]
make RENDER_API=RT64 -j4 not working
ivanb@DESKTOP-3JDV5U1 MSYS ~/render96ex
$ make RENDER_AP
make: cc: No such file or directory
make: *** [Makefile:47: n64graphics] Error 127
Traceback (most recent call last):
  File "/home/ivanb/render96ex/./extract_assets.py", line 286, in <module>
    main()
  File "/home/ivanb/render96ex/./extract_assets.py", line 156, in main
    subprocess.check_call(
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-s', '-C', 'tools/', 'n64graphics', 'skyconv', 'mio0', 'aifc_decode']' returned non-zero exit status 2.
Makefile:204: *** Failed to extract assets.  Stop.

**Comment by XxIvan2398Xx** [comment]
ivanb@DESKTOP-3JDV5U1 MINGW64 ~/render96ex
$ make RENDER_API=RT64 -j4
Failed to open baserom.us.z64! [Errno 2] No such file or directory: 'baserom.us.z64'
Makefile:204: *** Failed to extract assets.  Stop.

This is now what is showing

**Comment by TGRush** [comment]
this project will not compile unless you got a US copy of the game, in .z64 format, which is named `baserom.us.z64`

**Comment by thanone2** [comment]
where do you copy the rom to? (I have absolutely no idea where the folder for Render96ex even is located)
