### ISSUE TITLE
TAS Playback Broken

### ISSUE THREAD

**Issue by Craftyawesome** [Render96/Render96ex#31]
**Describe the bug**
When using the TAS playback (cont.m64) it does not play correctly. It seems to do some wrong inputs on file select and then delayed(?) because it doesn't change the camera like the working playback in a repo like sm64ex or sm64rt.

**To Reproduce**
Make sure save file 1 is empty and will play the intro upon selection
Download the old US 1 key TAS http://tasvideos.org/userfiles/info/37135408704300908
Rename to cont.m64 and put in the same directory as sm64
Run Render96

**Expected behavior**
For the TAS to match console, emu, and other ports

**Video**
Broken (Render96ex alpha)
https://cdn.discordapp.com/attachments/728112163297951835/844066816498466856/broken.webm

Working (sm64rt)
https://cdn.discordapp.com/attachments/728112163297951835/844066863721349150/Working.webm

**Desktop (please complete the following information):**
Windows 10 2004
6600k
GTX 1060

**Comment by DorfDork** [comment]
It will be broken because of certain patches are applied into the repo causing desync with TAS.
