### ISSUE TITLE
Problem compiling on raspberrypi

### ISSUE THREAD

**Issue by TotalCoolness** [Render96/Render96ex#38]
I'm trying to compile the windows build on a raspberry pi.

I get the following error :

`
 $ make -j4 WINDOWS_BUILD=1
make: Entering directory '/home/pi/supermario64/render64ex/Render96ex/tools'
make: Nothing to be done for 'default'.
make: Leaving directory '/home/pi/supermario64/render64ex/Render96ex/tools'
cc -c -O2   -I include -I build/us_pc -I build/us_pc/include -I src -I . -DDYNOS -DRAPI_GL=1 -DWAPI_SDL2=1 -DAAPI_SDL2=1 -DCAPI_SDL2=1 -DHAVE_SDL2=1 -I/usr/include/SDL2 -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -D_REENTRANT -DVERSION_US -D_LANGUAGE_C -DGIT_HASH="\"8e2eea10\"" -DNON_MATCHING -DAVOID_UB -DF3DEX_GBI_2E -fno-strict-aliasing -fwrapv -DEXT_OPTIONS_MENU -DFS_BASEDIR="\"res\"" -o build/us_pc/src/game/envfx_snow.o src/game/envfx_snow.c
src/game/mario_cheats.c:839:37: error: 'motos_geo' undeclared here (not in a function); did you mean 'mips_geo'?
     { bhvMotos,                     motos_geo,              "MOTOS",                        0,   40, 300, 0x00000000, 1, 0 }, // SPAMBA_MOTOS,
                                     ^~~~~~~~~
                                     mips_geo
cc -c -O2   -I include -I build/us_pc -I build/us_pc/include -I src -I . -DDYNOS -DRAPI_GL=1 -DWAPI_SDL2=1 -DAAPI_SDL2=1 -DCAPI_SDL2=1 -DHAVE_SDL2=1 -I/usr/include/SDL2 -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -D_REENTRANT -DVERSION_US -D_LANGUAGE_C -DGIT_HASH="\"8e2eea10\"" -DNON_MATCHING -DAVOID_UB -DF3DEX_GBI_2E -fno-strict-aliasing -fwrapv -DEXT_OPTIONS_MENU -DFS_BASEDIR="\"res\"" -o build/us_pc/src/game/hud.o src/game/hud.c
src/game/mario_cheats.c:840:37: error: 'friendly_blargg_geo' undeclared here (not in a function); did you mean 'bhv_friendly_blargg_init'?
     { bhvFriendlyBlargg,            friendly_blargg_geo,    "BLARGG",                       0,   40, 300, 0x00000000, 1, 0 }, // SPAMBA_BLARGG,
                                     ^~~~~~~~~~~~~~~~~~~
                                     bhv_friendly_blargg_init

[ snipped off more of the same]
`

Help would be appreciated if anyones managed to compile it on the Pi for PC.

**Comment by TotalCoolness** [comment]
Also similar problem on the Windows build:

`
src/game/mario_cheats.c:839:37: error: 'motos_geo' undeclared here (not in a function); did you mean 'mips_geo'?
  839 |     { bhvMotos,                     motos_geo,              "MOTOS",                        0,   40, 300, 0x00000000, 1, 0 }, // SPAMBA_MOTOS,
      |                                     ^~~~~~~~~
      |                                     mips_geo
src/game/mario_cheats.c:840:37: error: 'friendly_blargg_geo' undeclared here (not in a function); did you mean 'bhv_friendly_blargg_init'?
  840 |     { bhvFriendlyBlargg,            friendly_blargg_geo,    "BLARGG",                       0,   40, 300, 0x00000000, 1, 0 }, // SPAMBA_BLARGG,
      |                                     ^~~~~~~~~~~~~~~~~~~
      |                                     bhv_friendly_blargg_init
src/game/mario_cheats.c: In function 'cheats_spamba_spawn_object':
src/game/mario_cheats.c:1004:83: error: 'luigis_wing_cap_geo' undeclared (first use in this function); did you mean 'marios_wing_cap_geo'?
 1004 |             if (isLuigi()) obj->header.gfx.sharedChild = dynos_geo_get_graph_node(luigis_wing_cap_geo, true);
      |                                                                                   ^~~~~~~~~~~~~~~~~~~
      |                                                                                   marios_wing_cap_geo
src/game/mario_cheats.c:1004:83: note: each undeclared identifier is reported only once for each function it appears in
src/game/mario_cheats.c:1005:83: error: 'warios_wing_cap_geo' undeclared (first use in this function); did you mean 'marios_wing_cap_geo'?
 1005 |             if (isWario()) obj->header.gfx.sharedChild = dynos_geo_get_graph_node(warios_wing_cap_geo, true);
      |                                                                                   ^~~~~~~~~~~~~~~~~~~
      |                                                                                   marios_wing_cap_geo
src/game/mario_cheats.c:1010:83: error: 'luigis_cap_geo' undeclared (first use in this function)
 1010 |             if (isLuigi()) obj->header.gfx.sharedChild = dynos_geo_get_graph_node(luigis_cap_geo, true);
      |                                                                                   ^~~~~~~~~~~~~~
src/game/mario_cheats.c:1011:83: error: 'warios_cap_geo' undeclared (first use in this function); did you mean 'marios_cap_geo'?

`

**Comment by TGRush** [comment]
why are you exporting a windows build when you're compiling for a Pi?
see:
```
WINDOWS_BUILD=1
```
↑ this is **unneeded** unless youre actually building for Windows, and as long ad you run Mingw64 on Windows, it does this automatically anyways

**Comment by TotalCoolness** [comment]
I got it to work, the problem was the hd models werent working which I got from another site. Deleted them and it compiled fine.
