### ISSUE TITLE
Model Breaks When Put Into Render96ex-alpha (Followed Steps To Port SM64EX Models) And Model Is Still Broken

### ISSUE THREAD

**Issue by SonicTheHedgeHog64** [Render96/Render96ex#96]
**Describe the bug**
The Texels On The Custom Mario Model Are Broken.

**To Reproduce**
1. Go to https://cdn.discordapp.com/attachments/1194423615366631495/1194426403358244864/mario_definitiveEdition_Final_-_Kopie1.blend And Download Newest Fast64 Version, Get Blender
2. Load The Model With Blender And Set The Repo To The Render96ex-alpha Repo
3. Export The Model With Microcode F3DEX2/ZEX/LX2 And Have Bleed And Inline Mats On
4. Compile The Game

**Expected behavior**
Models Textures Work Fine

**Screenshots**
![image](https://github.com/Render96/Render96ex/assets/109289447/85a5872b-a6d4-47ae-80ba-c4c3fcfa8bfb)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Browser FireFox 
 - Version 121.0

**Comment by avereyishere** [comment]
uhm
